### ISSUE TITLE
Can I use short-cut?

### ISSUE THREAD

**Issue by kksworks** [fabiospampinato/vscode-open-in-application#10]
![img_009](https://user-images.githubusercontent.com/8262405/61919903-93b96e80-af92-11e9-815e-776188627d24.png)

I want to use shorcut.

thanks for your support.

**Comment by fabiospampinato** [comment]
Not possible unfortunately. That message is there for a reason.

**Comment by jascodes** [comment]
@fabiospampinato Is this restricted by vscode?

**Comment by fabiospampinato** [comment]
For binary files yeah, last time I checked there weren't APIs for fetching the path to the current binary file open in the editor.
