### ISSUE TITLE
[bug] If you choose nothing, the file will be opened in the default application

### ISSUE THREAD

**Issue by kanlukasz** [fabiospampinato/vscode-open-in-application#13]
I have multiple apps for .html files:

```
    "openInApplication.applications": {
      "html": [
        "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe",
        "C:/Program Files/Opera/launcher.exe"
      ]

    }
```

When you click:
![obraz](https://user-images.githubusercontent.com/30685349/80599198-da109200-8a2a-11ea-8d91-fe6e768c901f.png)

then you see:
![obraz](https://user-images.githubusercontent.com/30685349/80599225-e694ea80-8a2a-11ea-82fd-1385cca69c41.png)

And now, if you click "Escape" or click with the mouse anywhere, the file will open with the default system application
This is wrong because if I do not select an application from the list, the file should not be opened

**Comment by fabiospampinato** [comment]
Fixed in 1.0.6
