### ISSUE TITLE
why it cannot be assigned a shortcut ?

### ISSUE THREAD

**Issue by jiewangjs** [fabiospampinato/vscode-open-in-application#15]
After I pressed the shortcut assigned to it, this pops out. Does it mean that the functionality can not be achieved using keyboard shortcut but just context menu ?
![image](https://user-images.githubusercontent.com/11204422/133912586-49da0d3c-897b-43ac-9262-961d73b06d8d.png)

**Comment by fabiospampinato** [comment]
Last time I checked vscode provided no APIs for retrieving the path of the currently opened editor.
