### ISSUE TITLE
Cannot open Excel files

### ISSUE THREAD

**Issue by radumanolescu** [fabiospampinato/vscode-open-in-application#19]
I installed the open-in-application extension, but I cannot open local Excel files in Excel, using links such as
file:///C:\some\directory\some_file.xlsx

I tried various combinations of the settings below. I also tried exiting and re-opening VSCode. Every time, I get a warning that the file would be opened in VSCode and there is no appropriate editor for it

    "openInApplication.applications": {
        "*.xlsx": "Excel"
    }
    "openInApplication.applications": {
        "xlsx": "excel.exe"
    }
    "openInApplication.applications": {
        "xlsx": "Excel"
    }

**Comment by fabiospampinato** [comment]
Worth checking if you can open an excel file manually with the [`open` package](https://www.npmjs.com/package/open), if you can then there should be a way to get it to work with the app. Probably "Excel" or "excel.exe" are not the right names here 🤔 Besides isn't Excel configured as the default opener for those files? If so it should work without any configuration, and if it isn't maybe if you can configure that it will work with the extension.

**Comment by fabiospampinato** [comment]
I've rewritten the extension, worth checking if v2 fixes it. If it doesn't I'm going to need somebody to check if the `open` package can open the file.
