### ISSUE TITLE
Allow changing context entry to "Open in..."

### ISSUE THREAD

**Issue by Zyrsha** [fabiospampinato/vscode-open-in-application#3]
I modified the extension in order to change the menu entry to "Open in..."
It fits in much better with the rest of the menu. Also leaving out the "..." is misleading because it may prompt the user for the specific application.
The "Open in Application" is too strange, looked non-standard as if Microsoft did not make it.

**Comment by fabiospampinato** [comment]
This shouldn't be customizable. I agree that "Open in Application" is not the best in the world but I couldn't think of anything better, you say:

>  Also leaving out the "..." is misleading because it may prompt the user for the specific application.

By the same reasoning keeping "..." is also misleading because it may not prompt for anything, and by default that's what it will do.

> The "Open in Application" is too strange, looked non-standard as if Microsoft did not make it.

It'd be weird if it looked standard to be honest 🤔 

For the time being I think `Open in Application` is more appropriate than `Open in...`, it makes the extension more discoverable and more explicit. If you have another suggestion I'd be happy to hear it.

**Comment by Zyrsha** [comment]
Why shouldn't it be customizable? I have a folder called "Application" so this does not make any sense here. Seems like clicking on this is going to open the file in the App? ... in Application? What is Application? Nobody knows. Seems confusing. "Open in default application" is what you were actually intending, but the shortened version looks strange and unusual. Try searching Google for "Open in Application" - you will see it has never been used in any software. I asked for an option so I don't have to publish a "Open in..." extension on the marketplace.

**Comment by Zyrsha** [comment]
Why shouldn't it be customizable? I have a folder called "Application" so this does not make any sense here. Seems like clicking on this is going to open the file in the App? ... in Application? What is Application? Nobody knows. Seems confusing. "Open in default application" is what you were actually intending, but the half-shortened version is simply confusing and implies too much specifics regarding "Application". Try searching Google for "Open in Application" - you will see that this naming convention has never been used in any software. I asked for an option so I don't have to publish a "Open in..." extension on the marketplace.

**Comment by Zyrsha** [comment]
Why shouldn't it be customizable? I have a folder called "Application" so this does not make any sense here. Seems like clicking on this is going to open the file in the App? ... in Application? What is Application? Nobody knows. Seems confusing. "Open in default application" is what you were actually intending, but the half-shortened version is simply confusing and implies too much specifics regarding "Application". The English grammar of it does not really make sense in a way, because it's recursive and explicitly self referential. Try searching Google for "Open in Application" - you will see that this naming convention has never been used in any software. I asked for an option so I don't have to publish a "Open in..." extension on the marketplace.

**Comment by Zyrsha** [comment]
Why shouldn't it be customizable? I have a project folder called "Application" so this does not make any sense here. Seems like clicking on this is going to open the file in the App? ... in Application? What is Application? Nobody knows. Seems confusing. "Open in default application" is what you were actually intending, but the half-shortened version is simply confusing and implies too much specifics regarding "Application". The English grammar of it does not really make sense in a way, because it's recursive and explicitly self referential. Try searching Google for "Open in Application" - you will see that this naming convention has never been used in any software. I asked for an option so I don't have to publish a "Open in..." extension on the marketplace.

**Comment by fabiospampinato** [comment]
> Why shouldn't it be customizable?

What commands are named/labeled is decided by the extension, if we open up these things to customizability then absolutely anything should be customizable. Besides that label is set in `package.json`, we can't change that at run time.

>  I have a folder called "Application" so this does not make any sense here. Seems like clicking on this is going to open the file in the App? ... in Application? What is Application? Nobody knows.

I agree that it sounds weird, but I don't understand your example here, do you expect your files to be opened via a folder? 🤔"Application" is the default one for that extension, or the one you pick in case you configured the extension to ask you which application to use for that particular extension.

> "Open in default application" is what you were actually intending

No "Open in default application" would be plain _wrong_ since you can configure the extension to use other applications than the default one.

>  I asked for an option so I don't have to publish a "Open in..." extension on the marketplace.

You're absolutely free to do that. I'm not going to change that label until I can think of something that makes more sense to me.

**Comment by fabiospampinato** [comment]
Maybe what you want is an "Open in Default Application" extension, feel free to make that. This one is more general, that's way it's not named "Open in Default Application".

**Comment by Zyrsha** [comment]
> No "Open in default application" would be plain wrong since you can configure the extension to use other applications than the default one.

At least, "Open in..." is never wrong, even when I have an project directory structure called Application.

**Comment by fabiospampinato** [comment]
> At least, "Open in..." is never wrong, even when I have an project directory structure called Application.

The 3 dots imply that there's an action to be taken next, which is not always the case. This is wrong in my book.

Your directory structure is absolutely irrelevant.

**Comment by Zyrsha** [comment]
"This is wrong in my book" but it is not wrong in Microsoft's book. You will notice that if the user *might* be prompted, then they put the 3 dots. The "incorrect behavior" is prompting the user after failing to label that you were going to do so.

The 3 dots does not imply that you will be prompted by palette to take the next action. It implies *the modal context is going to change and your executed command will no longer return you back to the editor or focused area where the command was executed*

This applies to "File -> Open..." which does not prompt the user for a command. It also applies to "Debug -> New Breakpoint -> New Conditional Breakpoint..." which may or may not prompt the user depending on the context.

**Comment by Zyrsha** [comment]
"This is wrong in my book" but it is not wrong in Microsoft's book. You will notice that if the user *might* be prompted, then they put the 3 dots. The "incorrect behavior" is prompting the user after failing to label that you were going to do so.

The 3 dots does not imply that you will be prompted by palette to take the next action. It implies *the modal context is going to change, you may possibly be prompted for input, and your executed command will no longer return you back to the editor or focused area where the command was executed*

This applies to "File -> Open..." which does not prompt the user for a command. It also applies to "Debug -> New Breakpoint -> New Conditional Breakpoint..." which may or may not prompt the user depending on the context.

**Comment by fabiospampinato** [comment]
I don't care much about what Microsoft thinks to be honest.

You might be right in this regard that "Open in..." would be more appropriate than "Open in Application", but I'm personally not so sure about that, and also renaming the extension comes with its downsides. All things considered I don't think it's worth it renaming it to "Open in...".

**Comment by Zyrsha** [comment]
I think you're half right and I'm half wrong and it's actually a difficult one to think of the appropriate name for. You are good at arguing and I did not mind arguing with you.
